plugins {
    id 'com.android.application'
}

android {
    namespace 'com.estarx.vulkansample'
    compileSdk 34

    defaultConfig {
        applicationId 'com.estarx.vulkansample'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
                abiFilters 'arm64-v8a'
            }
        }
    }

    buildFeatures {
        buildConfig true
    }

    sourceSets {
        main {
            java {
                srcDirs 'src/main/java', '../../../platform/android/java'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
    }
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
}
